[package]
name = "llam"
version = "0.1.0"
edition = "2024"

[dependencies]
luarc = { path = "../luarc" }

log = "0.4.22"
url = "2.5.4"
serde = { version = "1.0.219", features=["derive"] }
serde_json = "1.0.140"
clap = { version = "4.5.38", features = ["derive"] }
dirs = "6.0.0"
dunce = "1.0.5"
env_logger = "0.11.8"
